### ISSUE TITLE
All `sagemath` third party mirrors are unaccessible

### ISSUE THREAD

**Issue by gordon-quad** [cschwan/sage-on-gentoo#445]
All links specified in `thirdpartymirrors` file for `sagemath` mirror are inaccessble:

lmona.de server times out and github mirror returns 404 when trying to install sage-7.4-r2:

```
$ wget -c http://www.lmona.de/files/sage/main-built.js.xz
--2016-11-30 11:54:30--  http://www.lmona.de/files/sage/main-built.js.xz
Resolving www.lmona.de... 131.246.164.21
Connecting to www.lmona.de|131.246.164.21|:80... failed: Connection timed out.
Retrying.

--2016-11-30 11:56:38--  (try: 2)  http://www.lmona.de/files/sage/main-built.js.xz
Connecting to www.lmona.de|131.246.164.21|:80... failed: Connection timed out.
Retrying.

--2016-11-30 11:58:47--  (try: 3)  http://www.lmona.de/files/sage/main-built.js.xz
Connecting to www.lmona.de|131.246.164.21|:80... failed: Connection timed out.
Retrying.

--2016-11-30 12:00:58--  (try: 4)  http://www.lmona.de/files/sage/main-built.js.xz
Connecting to www.lmona.de|131.246.164.21|:80... failed: Connection timed out.
Retrying.

--2016-11-30 12:03:09--  (try: 5)  http://www.lmona.de/files/sage/main-built.js.xz
Connecting to www.lmona.de|131.246.164.21|:80... ^C
$ wget -c https://github.com/sagemath/sage/archive/main-built.js.xz                                                                                                   130 ↵
--2016-11-30 12:04:24--  https://github.com/sagemath/sage/archive/main-built.js.xz
Resolving github.com... 192.30.253.112, 192.30.253.113
Connecting to github.com|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-11-30 12:04:24 ERROR 404: Not Found.

$ wget -c https://github.com/sagemath/sage/archive/patches/singular4.patch.xz                                                                                           8 ↵
--2016-11-30 12:04:38--  https://github.com/sagemath/sage/archive/patches/singular4.patch.xz
Resolving github.com... 192.30.253.113, 192.30.253.112
Connecting to github.com|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-11-30 12:04:38 ERROR 404: Not Found.
```

And I failed to find those files for sage-7.4-r2.ebuild anywhere else on the web.

**Comment by kiwifb** [comment]
Yes it looks down. I will see what I can do.

**Comment by kiwifb** [comment]
Just `www.lemona.de` is not accessible. But those files are not mirrored on other servers.

**Comment by andrey-smirnov** [comment]
Is it possible to get those files anywhere right now?

**Comment by kiwifb** [comment]
No. That has been something that I have been worrying about for a while. I don't really have mirrors or reliable long term storage. Suggestions welcome. I still have the files locally so it is not all lost.

**Comment by andrey-smirnov** [comment]
Could you, please, upload it somewhere (like any temporary file hosting like dump.bitcheese.net) for now as temporary solution and put links here?

**Comment by kiwifb** [comment]
Some files are too big for dump.bitcheese.net. I cannot really do anything for the next 9 hours (serious bed time in my time zone).

**Comment by kiwifb** [comment]
I need 600MB of space currently. Can be halved if I remove the `bin-html` and `bin-pdf` flags and people have to build the documentation.

**Comment by kiwifb** [comment]
If people have to build their own doc I need 100MB for various sources.

**Comment by gordon-quad** [comment]
I am definitely ok with building sources.

**Comment by kiwifb** [comment]
Various source files were hosted on lmona.de so they will still be missing to build the whole stack. I am getting some hosting sorted. cross fingers.

**Comment by kiwifb** [comment]
Please sync the overlay. I have a new host for the next few years. Report on success or failures please!

**Comment by gordon-quad** [comment]
there is no http://sagetrac.lipn.univ-paris13.fr/sage/patches/singular4.patch.xz file on new mirror. And also weirdly this server cuts off any connection which tries to download more than 10 Mb at once. But it still didn't stop me to download bin-html in ~9 tries.

**Comment by kiwifb** [comment]
OK my fault `singular4.patch` I didn't amend the SRC_URI properly. I'll take the other problem with my hosting friend. In the meantime you may have to use `USE="-bin-html html"`.

**Comment by kiwifb** [comment]
OK the "patches" bit should be fixed now if you sync.

**Comment by gordon-quad** [comment]
now it works, thank you

**Comment by kiwifb** [comment]
Does it download more than 10MB?

**Comment by gordon-quad** [comment]
I downloaded this file yesterday, but I could check again

**Comment by gordon-quad** [comment]
No, it still hangs after 10 Mb and you need to restart wget to continue.

**Comment by kiwifb** [comment]
That is a problem. Even if I drop pre-packaged doc my re-packed gap tarball is bigger than that I think.

**Comment by gordon-quad** [comment]
You can put a warning for +bin-html flag so people know that they possibly need to download it manually

**Comment by sonOfRa** [comment]
I think this is related: I'm currently trying to install sage, and I already reported #446 because the path to cubex was wrong. Portage is now failing to download sage itself:

`>>> Downloading 'http://sagetrac.lipn.univ-paris13.fr/sage/7.4.tar.gz'
--2016-12-14 16:26:11--  http://sagetrac.lipn.univ-paris13.fr/sage/7.4.tar.gz
Resolving sagetrac.lipn.univ-paris13.fr... 194.254.163.85
Connecting to sagetrac.lipn.univ-paris13.fr|194.254.163.85|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-12-14 16:26:11 ERROR 404: Not Found.
`

Fiddling with the path doesn't seem to yield any path that results in a suitable tarball being downloaded. Would it be possible to activate directory listing on http://sagetrac.lipn.univ-paris13.fr/sage/ so that one can see which files are present and which aren't?

**Comment by kiwifb** [comment]
Yes, it probably is. I updated `sagemirror` and possibly removed something I shouldn't have there. Looking at it.

**Comment by kiwifb** [comment]
@sonOfRa a898650c99cc66b44c97323338354caed2a5ad29 should fix the sage tarball download problem. I had set it as something a bit silly if I may say so myself.

**Comment by sonOfRa** [comment]
Yes, syncing the overlay fixed it, sage has been successfully built and is doing my math for me now. :+1:

**Comment by kiwifb** [comment]
This should all be fixed including interrupted downloads because wget/curl tries to get things too fast. Closing.
